import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const ailerons = localfont({
  src: [
    {
      path: "../../public/fonts/Ailerons.otf",
    }
  ],
  variable: "--font-aileron",
})

export const metadata: Metadata = {
  title: "Project Mars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ailerons.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
